# Generated by Django 4.0.4 on 2022-04-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название перевозки')),
                ('direction', models.CharField(max_length=100, verbose_name='Направление')),
                ('type', models.CharField(max_length=100, verbose_name='Тип груза')),
                ('time', models.DateField(verbose_name='Дата доставки')),
                ('weight', models.FloatField(verbose_name='Масса груза ')),
                ('measure_name', models.CharField(choices=[('Тн', 'Тн'), ('Кг', 'Кг')], default='Кг', max_length=20, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
