# Generated by Django 4.0.4 on 2022-04-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
